### ISSUE TITLE
SKQueue deprecation notice

### ISSUE THREAD

**Issue by daniel-pedersen** [daniel-pedersen/SKQueue#11]
So it seems like this library is still growing in popularity. I'm guessing the ease of use is appealing.

Some background: I wrote this library back in 2014 when Swift was still unstable and I needed kqueue functionality for a project. Today I would have used the [DispatchSource](https://developer.apple.com/documentation/dispatch/dispatchsource) API, which exposes kqueue functionality optimized for GCD.

But if y'all like this API I'll consider maintaining it.

**Comment by valdirunars** [comment]
Hey Daniel, great work btw 👍 
I was wondering, what other great solutions are you talking about?

**Comment by michaelradtke** [comment]
Hi Daniel, I like to thank you for your great work.
Please can you suggest another solution that can replace SKQueue?

**Comment by daniel-pedersen** [comment]
So the best solution would be to migrate from using `SKQueue` to [`DispatchSource`](https://developer.apple.com/documentation/dispatch). See the `makeFileSystemObjectSource` function.
