### ISSUE TITLE
New 1.3 release

### ISSUE THREAD

**Issue by MaxDesiatov** [daniel-pedersen/SKQueue#13]
Hey @daniel-pedersen, now that #12 is merged, would you mind tagging a new release? This would help packages depending on SKQueue, as they could specify a release tag in their dependencies instead of `master`. Depending on `master` directly sometimes leads to issues, especially when integrating SwiftPM dependencies with Xcode. Thanks!

**Comment by daniel-pedersen** [comment]
Done :)

**Comment by MaxDesiatov** [comment]
Awesome, thanks again!
