### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by antonsegerkvist** [daniel-pedersen/SKQueue#9]
Any thoughts on porting this to Swift 4?

Cheers

**Comment by daniel-pedersen** [comment]
The code itself is fully compatible with Swift 4 (i.e. `SKQueue.swift`). But I'll update the manifest right away.

**Comment by daniel-pedersen** [comment]
A Swift 4 compatible version of SKQueue is now on the develop branch. Since the Swift 4 package manager is not backwards-compatible, I've decided to release this version as Xcode 10 is officially released by Apple.

**Comment by antonsegerkvist** [comment]
Sounds good to me.

Best Regards
Anton Segerkvist

**Comment by daniel-pedersen** [comment]
On master
